### ISSUE TITLE
s02.mdの「ESP32とBME280との接続」の表にtypo？

### ISSUE THREAD

**Issue by tatsu1225** [ngi644/o_uitec_iot#1]
s02.mdの「ESP32とBME280との接続」の表にtypo？らしきものが
　SDIO -> SDO  
でしょうか？
https://github.com/ngi644/o_uitec_iot/blob/main/s02.md#esp32%E3%81%A8bme280%E3%81%A8%E3%81%AE%E6%8E%A5%E7%B6%9A

**Comment by ngi644** [comment]
ありがとうございます．修正しました．
